### PR TITLE
Code refactor for clearer project objectives

### PR DESCRIPTION
**Pull request by CeType**
- Separated two main chunks of code:LiSim and LiMap, LiSim should depend on LiMap but LiMap should be standalone, that's more or less implemented as of now 
- Works fine, except for a peculiar problem in the detection. Still commiting, will check against master branch and try to solve the problem

### CODE REVIEW

**Comment by CeType** [comment]
Oh I saw issue #23 
Am going to fix it in this branch

**Comment by fotisk07** [comment]
I have already fixed it don't worry

**Comment by fotisk07** [comment]
I'm gonna check on it tomorrow, not 100% sure I'll use that structure tho because I'm making the animation part rn and it has certain weird aspects structure wise

**Comment by CeType** [comment]
What I tried to do is at least separate the simulation and the actual Lidar code, because the latter should be clearly separated from the former so we can actually use it in our project

**Comment by CeType** [comment]
Also there's a main.py that principally uses ressources from across the package to do the job, giving a clear overview of the simulation process and separating the mapping unit from the main program loop.

**Comment by CeType** [comment]
As per my testing, it should be running the same now

**Comment by CeType** [comment]
If you validate it, I can do the conflict resolving if you want

**Comment by fotisk07** [comment]
Your code seems to work and is also very pretty so I trust you haven't screwed up something otherwise I'll eat your guts

**Comment by fotisk07** [comment]
So sure if you can do the conflict resolve it would be nice

**Comment by fotisk07** [comment]
I don't get why you use so many globals in your functions tho

**Review by fotisk07 — APPROVED** [review]
Everything seems great

**Comment by CeType** [comment]
The globals are module globals. It makes sense for _basePath because it should be shared by everything that must save something.
For logos im not that sure, but as it's supposed to be a constant pair of values, I made it global so if another function in map.py ever needs them, the variable will be shared (maybe add a mutator so that the user can enter custom values ?)

**Comment by fotisk07** [comment]
I see

**Comment by fotisk07** [comment]
I have started work on animation and executing the thing multiple times I'll have it finished by the end of the day

**Comment by fotisk07** [comment]
(I hate animations)

**Comment by CeType** [comment]
Done manually

**Pull request closed without merging**
