### PR TITLE
Integrate the path_gen to the program logic

### PR DESCRIPTION
**Pull request by CeType**
This should be good but wasn't tested yet

### CODE REVIEW

**Comment by fotisk07** [comment]
I don't unserstand your points parameter. If you already give it a list of points what are you asking the simulate function to give you?

**Comment by CeType** [comment]
It’s the set of points to measure, basically it’s a discretization of the path the lidar travels during the simulation with a LiDAR position and a measure angle associated with each frame.
Here I created a “one turn” function that wraps around the main path genereation function to easily recreate what was already there (ie. a static LiDAR with the laser rotating clockwise) but using the l main function, linear and circular paths are already implemented

**Comment by CeType** [comment]
Stems from dis: https://github.com/fotisk07/SI-Project/projects/3#card-28349605

**Comment by CeType** [comment]
Kan iu riviu dis pls

**Comment by fotisk07** [comment]
Can you resolve the conflicts?

**Review by fotisk07 — APPROVED** [review]
Looks fine

**Pull request merged**
